### ISSUE TITLE
add SME Intro PPT to the Getting Started page

### ISSUE THREAD

**Issue by stephaniefaith** [usds/SME-QA-Website#112]
Can we add this PPT to getting started? It can be called:

"PPT template to introduce Hiring Managers and SMEs to the process and time required"

[Intro Presentation on SME-QA for Participating SMEs and Hiring Managers.pptx](https://github.com/usds/SME-QA-Website/files/3880669/Intro.Presentation.on.SME-QA.for.Participating.SMEs.and.Hiring.Managers.pptx)

**Comment by stephaniefaith** [comment]
no rush on this @humancompanion-usds but i created this for OMB so thought it could be useful for other agencies

**Comment by humancompanion-usds** [comment]
@stephaniefaith - The one you linked to here had less slides so I ended up merging them so that the slides in this version were added to the version we had and organized them so that the time commitment and other next steps for SMEs were at the end. I also added the 1-pager (which is really 2 pages) to the toolkit so I think we're good here now with the availability of intro materials.
