### ISSUE TITLE
Getting Started: Discuss "rooted in the PD"

### ISSUE THREAD

**Issue by humancompanion-usds** [usds/SME-QA-Website#125]
Our page on identifying appropriate positions mentions PDs but doesn't talk about the flexibility that exists to use job analysis and have the JOA be rooted in the PD rather than using verbiage from the PD verbatim.

* [x] Stephanie to rewrite the current content
* [x] Stephanie to provide a pointer to the DEH page and sentence we want to quote.
* [x] Matt to link to the DEH page (and perhaps screenshot instead)

**Comment by stephaniefaith** [comment]
Identifying a Classified Position Description
Your position description (PD) should reflect adequate specialized experience to require the time and effort of SMEs. Rather than classifying a new PD, using a standardized PD is encouraged since you will be doing an in-depth job analysis workshop to link the PD to an accurate job announcement. The competencies identified through the job analysis workshop simply need to be rooted in the PD.  Page 3-12 of the updated DE Handbook clarifies: "Conditions of employment should be supported in the position description and/or by job analysis."

https://www.opm.gov/policy-data-oversight/hiring-information/competitive-hiring/deo_handbook.pdf
