### ISSUE TITLE
add sample project timeline

### ISSUE THREAD

**Issue by stephaniefaith** [usds/SME-QA-Website#148]
Several agencies have asked us for a sample project timeline. Will and I came up with this sample below, which could probably go at the bottom of this website page: https://smeqa.usds.gov/hiring-phases/getting-started/time-commitment/

**Example Timeline**
Week One: Job analysis workshop
Week Two: Circulate workshop output, draft job announcement, begin recruitment
Week Three: Post Job Announcement (until midnight after 100 applicants), SME resume review training
Week Four: SMEs conduct resume review
Week Five: HR reviews notes and sends tiebreakers to other SMEs
Week Six: HR reviews notes, begins scheduling interviews, and trains SMEs doing Interview 1
Weeks Seven, Eight, Nine: SMEs conduct interview 1. HR reviews notes, schedules round 2 interviews, and trains SMEs doing Interview 2.
Weeks Eight, Nine, and Ten: SMEs conduct interview 2; HR reviews notes
Weeks Eleven and Twelve: HR issues certs; hiring managers hold final placement interviews and tell HR which applicants they want
Week Thirteen: HR sends offers. Applicants confirm or decline within 48 hours. HR creates new certificates with next category for the HM to consider. Repeat process; once hiring manager is done, share certificate with other interested offices at the agency

**Comment by humancompanion-usds** [comment]
![Timeline](https://user-images.githubusercontent.com/52176351/74383972-45e54600-4dbe-11ea-94b3-e4ebdc170957.png)

Okay, here is the deal: This content kinda stinks. It's super wordy in some places and not in others. It's not entirely consistent. The content is making it rather difficult to turn this into something visually useful. I also tried an HTML table because I'd rather not condemn the content to just living in a graphic. But that too, given the overlaps at weeks 7-9 and 8-10 fouls up the table. This needs a rethink. 

We have some size constraints on the web page this is intended for that make a legible graphic a challenge given all of the text.

**Comment by humancompanion-usds** [comment]
![Screen Shot 2020-02-12 at 5 40 16 PM](https://user-images.githubusercontent.com/52176351/74384184-c146f780-4dbe-11ea-88e3-ee480f8089a6.png)

Here's the table. Note the tumor starting at the overlap.

**Comment by humancompanion-usds** [comment]
![Timeline-v2](https://user-images.githubusercontent.com/52176351/74446861-82f51b00-4e46-11ea-90a4-b48a14e00ec9.png)

Minimal variation. Working on another one that splits SME, HR, and hiring managers into lanes.

**Comment by humancompanion-usds** [comment]
![Timeline-v3](https://user-images.githubusercontent.com/52176351/74453453-6d84ee80-4e50-11ea-8cd0-84ca36bb129f.png)

Adds swimlanes for SMEs, HR, and hiring managers.

**Comment by stephaniefaith** [comment]
Thanks @humancompanion-usds for all these options! curious @wslack 's thoughts but from my perspective, the project managers who asked us this need something close to the first format but i totally hear and see your issue with it. i think i can get this down a lot more text wise to simplify it. should i try that here via text?

**Comment by stephaniefaith** [comment]
Suggested Timeline
Week One: Job analysis workshop
Week Two: Finalize competencies and interview questions, Prepare job announcement
Week Three: Post Job Announcement, Conduct SME Resume Review Training
Week Four: SMEs conduct resume review
Week Five: SMEs conduct resume review tiebreakers
Week Six: Schedule interviews, train SMEs on conducting interviews
Weeks Seven, Eight, Nine, Ten: SMEs conduct first and second interviews on a rolling basis. 
Weeks Eleven and Twelve: HR issues certs; hiring managers interview and make selections
Week Thirteen: HR sends offers. Applicants confirm or decline within 48 hours. HR creates new certificates with next category for the HM to consider. Repeat process.

**Comment by stephaniefaith** [comment]
@humancompanion-usds I tried to truncate this a bit

**Comment by humancompanion** [comment]
@stephaniefaith - If the ask was from project managers then perhaps a project plan gantt chart is what they are after? If so, that's not a really a timeline. A timeline generally has dates and events that happen over time and is usually looking back rather than forward. Thus I think trying to merge a task list or project plan into a timeline graphic format has not been successful. 

When I think project plan this is more what I'd be after:
![project-plan](https://user-images.githubusercontent.com/352987/74460219-8befe780-4e5a-11ea-9d23-ed8aab66645d.png)

If width isn't a constraint, other than fitting it on one landscape page, then I think we could accommodate this as a downloadable template. But forcing it into a portrait layout on a web page doesn't really work for a gantt chart.

**Comment by humancompanion-usds** [comment]
Okay, given that we seem to want a list of tasks, I've attempted a version that combines a visualization and the list of tasks in each week.

![timeline-v4](https://user-images.githubusercontent.com/352987/74463305-a6788f80-4e5f-11ea-9d87-fceccabdf098.png)

**Comment by stephaniefaith** [comment]
oh i kinda love that. let's let @wslack comment too since he's been asked for this as well.

**Comment by sstrassberg** [comment]
@humancompanion-usds I agree with @stephaniefaith that the Gantt chart accompanied with the text of tasks works well. I think what would complete it is to use icons for SME, HR and HM to be placed on the task they would be doing on the chart. This would marry the swimlanes you made in the portrait mode graphic. I can think about what those icons might look like.

**Comment by wslack** [comment]
I like https://github.com/usds/SME-QA-Website/issues/148#issuecomment-585889211 (Matt's most recent), though with larger captions and icons - we don't need precision as much as a general sense of timing. I don't think participants need to know who is doing which step in this chart.
