### ISSUE TITLE
Rewrite of "Do not conduct a separate HR min qual review" message

### ISSUE THREAD

**Issue by humancompanion-usds** [usds/SME-QA-Website#150]
We'd like to revise the "Do not conduct a separate HR min qual review" message to focus on that just being an entry into the passing score exam.

**Comment by stephaniefaith** [comment]
After SMEs have finished reviewing resumes, HR is not required to conduct a separate qualifications review since this process relies on the judgement of SMEs. HR instead plays a strong role in ensuring the justification statement traces back to a required competency or proficiency. In this process, being minimally qualified only gains applicants entry into the pass/fail interview- it does not guarantee applicants preference points. See DE handbook 4-2, and 5-23, 24"
