### ISSUE TITLE
Change Results card to Getting Started Card and use map with flag/pin icons

### ISSUE THREAD

**Issue by sstrassberg** [usds/SME-QA-Website#266]
@humancompanion-usds Stephanie would like to replace the results card with a getting started card using an icon like this map route with flag and pin. She thinks the results page is the worst page on the site right now. However, you also made a Getting Started button, so this seems like it is redundant.

![noun_path_1929266](https://user-images.githubusercontent.com/48692564/88705893-262caa80-d0de-11ea-9512-04db45526128.jpg)

**Comment by humancompanion-usds** [comment]
I agree the results page is poor but I'd like to fix that rather than try to route around it. I've created an issue for that and plan to work on it: https://github.com/usds/SME-QA-Website/issues/268

Also, those 3 items are answering the question above it: "Is SME-QA right for you?" Getting Started does not answer that question.

**Comment by sstrassberg** [comment]
@humancompanion-usds Going to close this issue since we have discussed and agree that this shouldn't change anymore because you are improving the results page.
