### ISSUE TITLE
Add to website: DOI competancies

### ISSUE THREAD

**Issue by wslack** [usds/SME-QA-Website#92]
(we should have added these to the packet yesterday but they should be on the website as well)

**Comment by wslack** [comment]
replaces https://github.com/usds/SME-QA/issues/1020

**Comment by humancompanion-usds** [comment]
Oooohhkay. The "Sample Competencies and Proficiency Levels" that we just sent to the printer do not at all match what we have on the web site. I'm no longer certain which is "correct". Hoping @sharmaneil can weigh in and steer me here. Here's what each version has:

### SME toolkit sent to the printer for the training has:
1. Remote Work (meets & exceeds)
2. Engineering Considerations (meets & exceeds)
3. Information Architecture (meets & exceeds)
4. The DOI Competencies and proficiencies (Unfamiliar, familiar, experienced master)

### Web site PDF (and Word doc)
1. Analytical ability
2. Stakeholder Engagement
3. Superior EQ
4. Team Building
5. Customer Service and Support
6. Technical Communication
7. Data Analysis
8. Systems and Networking
9. Troubleshooting
10. Incident and Change Management
11. Product Delivery
12. Engineering Considerations
13. Product Design

All of those have the 4 proficiency levels (Unfamiliar, familiar, experienced master). Those look like perhaps a mash up of USDS and HHS? No clue really.

Not sure which action to take. Should I:

1. Make the website match what we sent to the printer?
2. Append the DOI competencies to the end of the web site PDF (I don't know where the Word version would be but, the site links to the PDF so that's fine for now)?
3. Some other thing

Also, the top description we wrote for the training materials we sent to the printer is misleading. We wrote:

> While the formats differ, you can see that the common aspects are:
> • A useful, brief description of the competency.
> • Two proficiency levels for “Meets” and “Exceeds”.

While that's true of the first 3 competencies that we wrote, it's not true for all of the DOI competencies which have 4 proficiency levels. I think we've made this clear as mud as to which folks are supposed to create: 2 or 4 levels. Can we decide and then be consistent? Or if we've decided "it's 2 unless you are hiring for multi-grade" then we need a distinct issue to go make all of the changes necessary across the site and toolkit materials to make that our recommendation.

**Comment by humancompanion-usds** [comment]
Okay, talked to Stephanie and she would like to keep what is on the website and add the DOI competencies as a distinct document which is an example of Job Analysis Workshop Output. One caveat: The DOI competency doc does not have their proficiency levels. I'll talk to the team tomorrow about whether those need to be added as well.

**Comment by humancompanion-usds** [comment]
Deployed. Neil reviewed. I cleaned up the sample competencies and normalized them to only have meets and exceeds proficiency levels.
